// <auto-generated />
using System;
using fitness_factor_api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace fitness_factor_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fitness_factor_api.Entities.Attendance", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CheckedIn").HasColumnType("datetime2");
                b.Property<DateTime?>("CheckedOut").HasColumnType("datetime2");
                b.Property<int>("GymId").HasColumnType("int");
                b.Property<int>("MemberId").HasColumnType("int");
                b.Property<string>("Source").HasMaxLength(10).HasColumnType("nvarchar(10)");
                b.HasKey("Id");
                b.HasIndex("MemberId", "CheckedOut");
                b.HasIndex("MemberId", "CheckedIn");
                b.ToTable("Attendances");
            });

            modelBuilder.Entity("fitness_factor_api.Entities.Gym", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<decimal>("Latitude").HasColumnType("decimal(10,8)");
                b.Property<decimal>("Longitude").HasColumnType("decimal(11,8)");
                b.Property<string>("Name").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<int>("RadiusMeters").HasColumnType("int");
                b.HasKey("Id");
                b.ToTable("Gyms");
                b.HasData(new { Id = 1, Name = "Fitness Factor", Latitude = 3.1390m, Longitude = 101.6869m, RadiusMeters = 50 });
            });

            modelBuilder.Entity("fitness_factor_api.Entities.Member", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("FcmToken").HasColumnType("nvarchar(max)");
                b.Property<string>("Name").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Phone").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.HasKey("Id");
                b.HasIndex("Phone").IsUnique();
                b.ToTable("Members");
            });

            modelBuilder.Entity("fitness_factor_api.Entities.Attendance", b =>
            {
                b.HasOne("fitness_factor_api.Entities.Gym", "Gym")
                    .WithMany("Attendances").HasForeignKey("GymId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("fitness_factor_api.Entities.Member", "Member")
                    .WithMany("Attendances").HasForeignKey("MemberId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Gym");
                b.Navigation("Member");
            });

            modelBuilder.Entity("fitness_factor_api.Entities.Gym", b =>
                b.Navigation("Attendances"));

            modelBuilder.Entity("fitness_factor_api.Entities.Member", b =>
                b.Navigation("Attendances"));
#pragma warning restore 612, 618
        }
    }
}
